name: CI

on:
  push:
    branches: [main, test/github-actions]
  pull_request:
    branches: [main, test/github-actions]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bun runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint TypeScript
        run: bun run lint

      - name: Run unit tests
        run: bun run test

      - name: Build for production
        run: bun run build
